# Generated by Django 3.0.6 on 2020-05-12 08:26

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='chek',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Selling',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=255)),
                ('seller', models.CharField(default='', max_length=255)),
                ('body', models.TextField(default='')),
                ('selling_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('date', models.DateTimeField(default=datetime.datetime(2020, 5, 12, 15, 26, 6, 225762))),
                ('duedate', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SellingAuction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auctioner', models.CharField(default='', max_length=255)),
                ('auction_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('date', models.DateTimeField(default=datetime.datetime(2020, 5, 12, 15, 26, 6, 226794))),
            ],
            options={
                'ordering': ['-auction_price'],
            },
        ),
        migrations.CreateModel(
            name='SellingImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_name', models.CharField(default='', max_length=255)),
                ('image', models.ImageField(blank=True, default='', null=True, upload_to='asset_image')),
                ('selling', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_images', to='selling.Selling')),
            ],
        ),
    ]
