# Generated by Django 2.1.7 on 2020-04-02 05:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selling', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='selling',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 2, 12, 52, 48, 537335)),
        ),
    ]
