# Generated by Django 3.0.6 on 2020-05-12 09:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selling', '0002_auto_20200512_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selling',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 12, 16, 6, 35, 239263)),
        ),
        migrations.AlterField(
            model_name='selling',
            name='duedate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sellingauction',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 12, 16, 6, 35, 240265)),
        ),
    ]
