# Generated by Django 2.1.7 on 2020-04-07 09:44

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('selling', '0002_selling_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='SellingAuction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auctioner', models.CharField(default='', max_length=255)),
                ('auction_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('date', models.DateTimeField(default=datetime.datetime(2020, 4, 7, 16, 44, 1, 640791))),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='selling',
            name='seller',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='selling',
            name='selling_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='selling',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 7, 16, 44, 1, 639780)),
        ),
        migrations.AddField(
            model_name='sellingauction',
            name='selling',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_auctions', to='selling.Selling'),
        ),
    ]
