# Generated by Django 3.0.6 on 2020-05-07 06:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selling', '0003_auto_20200407_1644'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sellingauction',
            options={'ordering': ['-auction_price']},
        ),
        migrations.AlterField(
            model_name='selling',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 7, 13, 52, 50, 247137)),
        ),
        migrations.AlterField(
            model_name='sellingauction',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 7, 13, 52, 50, 248139)),
        ),
    ]
