# Generated by Django 2.1.7 on 2020-05-11 10:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selling', '0004_auto_20200507_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selling',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 11, 17, 14, 13, 733435)),
        ),
        migrations.AlterField(
            model_name='sellingauction',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 11, 17, 14, 13, 734432)),
        ),
    ]
